### ISSUE TITLE
Run environment locally to check that it is working

### ISSUE THREAD

**Issue by linuswagner** [CloudScheduling/opendc#1]
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1xgmktn) by [Unito](https://www.unito.io)

**Comment by linuswagner** [comment]
@MaxiStefan can you produce some kind of short manual to set the environment up once you're done?

**Comment by MaxiStefan** [comment]
Yes, the plan is to get workflow conceptual model done, then workflow engine understood, and then ill run the simulator in the IDE. I will after that make a tutorial for the IDE
